### PR TITLE
add timezone support for calendar

### PR DESCRIPTION
**Pull request by frostli**
While there is timezone support for 'today' and works well in day view, I found the dates on monthly view can be off since they are not timezone-aware. This pull-request makes sure if timezone is passed, it is respected in monthly view as well.

### CODE REVIEW

**Comment by paltman** [comment]
Can you fix the lint error `pinax/calendars/adapters.py:6:1: E302 expected 2 blank lines, found 1`?

**Comment by frostli** [comment]
Addressed the lint issue. Thank you.

**Comment by ossanna16** [comment]
@paltman Can this be merged?

**Comment by paltman** [comment]
@frostli thanks!

**Pull request merged**
